### ISSUE TITLE
Make the proximate word distance configurable

### ISSUE THREAD

**Issue by stenskjaer** [stenskjaer/samewords#1]
It currently searches for word matches in 30 words on each side of the pivot word. This should be adjustable.

**Comment by floriandk** [comment]
Would it be possible to determine this value in characters instead of in words? One can usually get quite a precise count of the average or maximum width of the text block in an edition while word lengths vary heavily.

**Comment by stenskjaer** [comment]
As it is constructed now, it is not trivial. But of course, anything can be done. 

I just wonder whether it is so important. Of course we don't want the whole text filled with `\sameword{}` macros, so we need to limit them to the relevant context. But I prefer to mark too much rather than too few, so I don't see it as a big issue. But sure, it would be nice if you could be sure it only annotates just the relevant part of the context.

But some editions may have very long or short lines where it makes sense to adjust the context length.

**Comment by floriandk** [comment]
This would definitely only be a very minor improvement in terms of readability of the source and perhaps LaTeX runtime. So if it is a considerable amount of work, please don't bother!

**Comment by stenskjaer** [comment]
I don't think I will do this now, but if it becomes a problem (performance, mostly) I'll look into it.

**Comment by stenskjaer** [comment]
Because of the rewrite of the whole system this is now a really trivial problem to solve, so making it configurable was a no-brainer.

I have also reduced the default distance from 30 to 20 as you will rarely get more then 15 words in an average line on A4 pages with sensible margins.
