### ISSUE TITLE
handbook

### ISSUE THREAD

**Issue by maieul** [stenskjaer/samewords#14]
Write an short presentation/an handbook to be published on http://geekographie.maieul.net

**Comment by stenskjaer** [comment]
I would love to do that. I will work on it as soon as I have closed the current issues.

**Comment by stenskjaer** [comment]
@maieul: I have not created a simple documentation, which is at http://samewords.readthedocs.io/. Do you want me to create a description for your website too? I can make it short, maybe with a couple of examples.

And then I will of course also refer to the actual documentation.

But actually I am contemplating announcing it on a mailing list or two to see if there should be someone who would want to give some feedback on it. 
Do you think we should put a note up on your website at the same time would you prefer it done in a different way?
