### ISSUE TITLE
successive identical words only marked once (vers. 0.2.7 branch "issue-19")

### ISSUE THREAD

**Issue by floriandk** [stenskjaer/samewords#20]
```latex
\documentclass[draft]{article}

\usepackage[series={A},nofamiliar,noeledsec,noledgroup]{reledmac}

\begin{document}

\beginnumbering
\pstart
word
word
word
word
word
word
word
word
word
\edtext{word}{\Afootnote{statement}} %A
word
word
word
word
word
word
\edtext{word}{\Afootnote{statement}} %A
word
word
\pend
\endnumbering


\end{document}
```

results in

```latex
\documentclass[draft]{article}

\usepackage[series={A},nofamiliar,noeledsec,noledgroup]{reledmac}

\begin{document}

\beginnumbering
\pstart
\sameword{word}
word
a
b
c
\edtext{\sameword[1]{word}}{\Afootnote{statement}} %A
\sameword{word}
word
\sameword{word}
word
\sameword{word}
word
\edtext{\sameword[1]{word}}{\Afootnote{statement}} %A
\sameword{word}
word
\pend
\endnumbering


\end{document}
```

I think I remember that this wasn't a problem earlier but I'm not completely sure.

**Comment by stenskjaer** [comment]
That was one of the more embarrassing bugs. Thanks!

It should be solved in the issue-20 branch. Hopefully you can confirm that.

By the way: I don't really understand your error report. What I see when I run it before the change (on issue-19) is the following:

```
\documentclass[draft]{article}

\usepackage[series={A},nofamiliar,noeledsec,noledgroup]{reledmac}

\begin{document}

\beginnumbering
\pstart
\sameword{word}
word
\sameword{word}
word
\sameword{word}
word
\sameword{word}
word
\sameword{word}
\edtext{\sameword[1]{word}}{\Afootnote{statement}} %A
\sameword{word}
word
\sameword{word}
word
\sameword{word}
word
\edtext{\sameword[1]{word}}{\Afootnote{statement}} %A
\sameword{word}
word
\pend
\endnumbering


\end{document}
```

So I don't see this thing with the `a b c`, that you report:
```
\beginnumbering
\pstart
\sameword{word}
word
a
b
c
\edtext{\sameword[1]{word}}{\Afootnote{statement}} %A
```

Is that actually the output or did I misunderstand something?

**Comment by floriandk** [comment]
> By the way: I don't really understand your error report. What I see when I run it before the change (on issue-19) is the following: […]

Oh, I'm sorry, that's just a sloppy copy-paste error from another testfile. Actually my result is precisely the one you get.

> It should be solved in the issue-20 branch. Hopefully you can confirm that.

I will test this an the others hopefully tomorrow; unfortunately I didn't get around to do it today.

**Comment by floriandk** [comment]
Also included in branch issue-24, isn't it? At least compiling with it works for me.

**Comment by stenskjaer** [comment]
Awesome!
