### ISSUE TITLE
context_distance not read from json file (vers. 0.2.7 branch "issue-19")

### ISSUE THREAD

**Issue by floriandk** [stenskjaer/samewords#22]
Running with `--config-file` the value for `context_distance` is not considered.
Modifying `settings.py` works though, so this is very low priority for me.

(Other settings from the same json-file like `exclude_macros` are considered as expected.)

**Comment by stenskjaer** [comment]
You are right. I believe that also should work now. Right?

**Comment by floriandk** [comment]
Working with branch issue-24
