### ISSUE TITLE
sensitive_context_match isn't false by default and has some problems

### ISSUE THREAD

**Issue by Padlina** [stenskjaer/samewords#36]
This paragraph won't get annotated without setting the sensitive_context_match parameter to false in a config file:
```
\pstart
A word with \edtext{a word}{\Afootnote{another D}} after it.
\pend
```

Moreover, once the paragraph is annotated, the resulting code is like this:
```
\pstart
\sameword{A} \sameword{word} with \edtext{\sameword[1]{a} \sameword[1]{word}}{\Afootnote{another D}} after it.
\pend
\pstart
\sameword{a} \sameword{word} with \edtext{\sameword[1]{a} \sameword[1]{word}}{\Afootnote{another D}} after it.
\pend
```

but, once compiled, the two critical notes are different:
```
6 a word2] another D
7 a2 word2 ] another D
```

And if you put the parameter multiword on true, the resulting code is this:
```
\pstart
\sameword{A word} with \edtext{\sameword[1]{a word}}{\Afootnote{another D}} after it.
\pend
\pstart
\sameword{a word} with \edtext{\sameword[1]{a word}}{\Afootnote{another D}} after it.
\pend
```

but, again, the two critical notes are different:
```
6 a word] another D
7 a word2] another D
```

**Comment by stenskjaer** [comment]
I suspect that the reason the case sensitivity is not enfored is because of *reledmac*. This is not clear from my documentation, but you have to enable case sensitivity in reledmac with the command `swcaseinsensitive`.

Example: 
```
\documentclass{article}

\usepackage[swcaseinsensitive]{reledmac}

\begin{document}

\beginnumbering
\pstart
\sameword{A word} with \edtext{\sameword[1]{a word}}{\Afootnote{another D}} after it.
\pend
\pstart
\sameword{a word} with \edtext{\sameword[1]{a word}}{\Afootnote{another D}} after it.
\pend
\endnumbering

\end{document}
```

That gives me the app
```
1 a word2 ] another D 
2 a word2 ] another D
```

The other thing about the wrong default behaviour (compared to the documentation) is a mistake. 
Both these things should be adressed.

**Comment by stenskjaer** [comment]
I have updated the documentation so that it should not reflect my original intention of having sensitive matching be the default.

The update is reflected on https://samewords.readthedocs.io/en/latest/configuration.html.

**Comment by stenskjaer** [comment]
Ahh -- maybe I should wait with closing the issue until you have confirmed that you think it makes sense now.

**Comment by Padlina** [comment]
First of all, Happy new yeay!
Then, yes, it make sense to me. The only thing is that I have a problem with the swcaseinsensitive option:
! LaTeX Error: Unknown option `swcaseinsensitive' for package `reledmac'.
But I assume that this is something due to my latex configuration. So, I'll close this issue.
