### ISSUE TITLE
missing some words

### ISSUE THREAD

**Issue by floriandk** [stenskjaer/samewords#41]
```latex
\documentclass{article}
\usepackage[series={A},nofamiliar,noeledsec,noledgroup]{reledmac}

\begin{document}

\beginnumbering
\pstart
word 
\edtext{and}{\Afootnote{C1–6.}}
word and
\pend
\endnumbering 

\end{document}
```

is annotated to

```latex
\documentclass{article}
\usepackage[series={A},nofamiliar,noeledsec,noledgroup]{reledmac}

\begin{document}

\beginnumbering
\pstart
word 
\edtext{\sameword[1]{and}}{\Afootnote{C1–6.}}
word \sameword{and}
\pend
\endnumbering 

\end{document}
```

instead of correct 

```latex
\documentclass{article}
\usepackage[series={A},nofamiliar,noeledsec,noledgroup]{reledmac}

\begin{document}

\beginnumbering
\pstart
\sameword{word} 
\edtext{\sameword[1]{and}}{\Afootnote{C1–6.}}
\sameword{word} \sameword{and}
\pend
\endnumbering 

\end{document}
```

**Comment by stenskjaer** [comment]
Why do you want it to annotate the "word" tokens? It only annotates words that occur in an `edtext` annotation (either all of it or the first and last, depending on the situation) to disambiguate from other words in the text. Words that simply occur close to each other don't need disambiguation.

So when there is not `\edtext{}` with "word" than it won't annotate them.

**Comment by floriandk** [comment]
I'm sorry, you are certainly right! I was obviously confused when creating this issue. Please disregard it.
