### ISSUE TITLE
Problems with Mac CR and Win CRLF linebreaks

### ISSUE THREAD

**Issue by stenskjaer** [stenskjaer/samewords#9]
When files are saved with Win CRLF or Mac CR linebreaks the output is garbled, containing only the beginning or end of the document.

From issue #6.

**Comment by stenskjaer** [comment]
This should be solved in [issue-9](https://github.com/stenskjaer/samewords/tree/issue-9).

**Comment by floriandk** [comment]
Different linebreaks CRLF/CF/LF give the same correct results
